spring:
  profiles:
    active: local
  data:
    elasticsearch:
      hosts: 10.146.0.3,10.146.0.4,10.146.0.5,10.146.0.6
      port: 9200
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672

---

spring:
  profiles:
    active: dev
  data:
    elasticsearch:
      hosts: 10.146.0.3,10.146.0.4,10.146.0.5,10.146.0.6
      port: 9200
  rabbitmq:
    host: 10.140.0.2
    username: guest
    password: guest
    port: 5672
